# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Tyson Crosbie
  admin_email: tyson@tysoncrosbie.com
  admin_password: password
  secret_key_base: ac4ee0ad8966b02a4ac1d3d5ca644004ecc67c4bd57fc0319e76129f81a482f9e9266a0f3ba18b04372f7e22fbbb417ea84724f45edb2520c287ab12afc3d83e

test:
  domain_name: example.com
  secret_key_base: ac4ee0ad8966b02a4ac1d3d5ca644004ecc67c4bd57fc0319e76129f81a482f9e9266a0f3ba18b04372f7e22fbbb417ea84724f45edb2520c287ab12afc3d83e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
